<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CPS-LAP" name="EFT(failed)" tests="1" failures="1" timestamp="26 Jul 2016 05:44:39 GMT" time="0.034" errors="0">
  <testcase name="test3" time="0.012" classname="TestNG.ExeFailedTest3">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at TestNG.ExeFailedTest3.test3(ExeFailedTest3.java:10)
	at TestNG.RerunFailedTest.main(RerunFailedTest.java:16)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- EFT(failed) -->
